// Concatenates the drizzle-kit SQL migrations into a TypeScript module so the
// in-memory PGlite database (demo mode) can create the schema without reading
// files at runtime.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("../drizzle/", import.meta.url).pathname;
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".sql"))
  .sort();
const statements = files
  .flatMap((f) => readFileSync(join(dir, f), "utf8").split("--> statement-breakpoint"))
  .map((s) => s.trim().replace(/;$/, ""))
  .filter(Boolean);
const sql = statements.join(";\n") + ";";

const out = `// Generated by scripts/embed-schema.mjs from drizzle/*.sql. Do not edit.\nexport const SCHEMA_SQL = ${JSON.stringify(sql)};\n`;
writeFileSync(new URL("../src/db/schema.sql.ts", import.meta.url), out);
console.log(`Embedded ${statements.length} statements from ${files.length} migration file(s)`);
